# Generated by Django 4.2.1 on 2023-05-25 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_for', models.CharField(max_length=30, unique_for_date=True, verbose_name='for')),
                ('to', models.CharField(max_length=30, unique_for_date=True, verbose_name='to')),
                ('amount', models.FloatField()),
                ('on', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('of_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='group.group')),
            ],
        ),
    ]
