# Generated by Django 4.2.1 on 2023-05-25 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.CharField(max_length=30, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(max_length=30, verbose_name='for'),
        ),
    ]
