# Generated by Django 4.2.1 on 2023-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_transaction_on_alter_transaction_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.CharField(max_length=60, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(max_length=60, verbose_name='for'),
        ),
    ]
