# Generated by Django 4.2.1 on 2023-06-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_remove_transaction_added_transaction_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='added_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
