# Generated by Django 4.2.1 on 2023-07-02 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_alter_transaction_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='share_to',
            field=models.ManyToManyField(related_name='share_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
