# Generated by Django 4.2.3 on 2023-08-01 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0008_transaction_share_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="maintainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintaining_groups",
                related_query_name="maintaining_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Savings Account Maintainer",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="savings",
            field=models.IntegerField(default=0, verbose_name="Savings"),
        ),
    ]
