# Generated by Django 4.2.4 on 2023-08-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0009_group_maintainer_group_savings"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="inactive_members",
            field=models.ManyToManyField(
                blank=True, related_name="inactive_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="maintainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintaining_groups",
                related_query_name="maintaining_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Savings Account Maintainer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="of_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="group.group",
            ),
        ),
    ]
