# Generated by Django 4.2.5 on 2023-09-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0010_group_inactive_members_alter_group_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                db_index=True,
                error_messages={
                    "unique": "A group with that groupname already exists."
                },
                max_length=30,
                unique=True,
                verbose_name="Group Name",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="savings",
            field=models.PositiveIntegerField(default=0, verbose_name="Savings"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="of_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                related_query_name="transactions",
                to="group.group",
            ),
        ),
    ]
