name: Room Manger Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_HOST_USER : ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD : ${{ secrets.EMAIL_HOST_PASSWORD }}
      DB_type : ${{ secrets.DB_type }}
      DEBUG : ${{ secrets.DEBUG }}
      
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build & apply migrations project
      run: |
        if [ $DB_type == local ]; then python manage.py migrate; fi
        python manage.py migrate
    
        
    - name: Test with django test
      run: |
        # Set Django environment variables
        export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
        export DATABASE_URL=$DATABASE_URL
        export EMAIL_HOST_USER=$EMAIL_HOST_USER
        export EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        export DB_type=$DB_type
        export DEBUG=$DEBUG

        python manage.py test

